name: Metrics
on:
   # Schedule daily updates
   schedule: [{cron: "0 0 * * *"}]
   # (optional) Run workflow manually
   workflow_dispatch:
   # (optional) Run workflow when pushing on master/main
   push: {branches: ["master", "main"]}
jobs:
   github-metrics:
     runs-on: ubuntu-latest
     environment: 
       name: production
     permissions:
       contents: write
     steps:
       - uses: lowlighter/metrics@latest
         with:
            token: ${{ secrets.METRICS_TOKEN }}
            # Options
            user: realyushi
            template: classic
            base: header, activity, community, repositories, metadata
            base_indepth: yes
            config_timezone: Pacific/Auckland
            plugin_16personalities: yes
            plugin_16personalities_scores: yes
            plugin_16personalities_sections: personality
            plugin_16personalities_url: https://www.16personalities.com/profiles/intp-a/m/hqoobjncy
            plugin_anilist: yes
            plugin_anilist_limit: 2
            plugin_anilist_limit_characters: 22
            plugin_anilist_medias: anime
            plugin_anilist_sections: favorites
            plugin_anilist_shuffle: yes
            plugin_anilist_user: qs8cys
            plugin_introduction: yes
            plugin_introduction_title: yes
            plugin_languages: yes
            plugin_languages_analysis_timeout: 15
            plugin_languages_analysis_timeout_repositories: 7.5
            plugin_languages_categories: markup, programming
            plugin_languages_colors: github
            plugin_languages_limit: 8
            plugin_languages_recent_categories: markup, programming
            plugin_languages_recent_days: 14
            plugin_languages_recent_load: 300
            plugin_languages_sections: most-used
            plugin_languages_threshold: 0%
            plugin_topics: yes
            plugin_topics_limit: 15
            plugin_topics_mode: starred
            plugin_topics_sort: stars
            plugin_leetcode: yes
            plugin_leetcode_limit: 10
            plugin_leetcode_user: realYushi
            plugin_leetcode_sections: solved, skills, recent
            plugin_screenshot: yes
            plugin_screenshot_title: XKCD of the day
            plugin_screenshot_url: https://xkcd.com
            plugin_screenshot_selector: "#comic img"

